### ISSUE TITLE
Is the div operator correct?

### ISSUE THREAD

**Issue by ThomasA** [epfl-lts2/pyunlocbox#15]
I am going through the code in this package in detail as part of working on #13. Looking at the `operators.div` operator, I notice this:
https://github.com/epfl-lts2/pyunlocbox/blob/ee37c50586a445e2a8d851028d5e878a16164e89/pyunlocbox/operators.py#L155-L158
If I try to follow the logic of the lines 155-157, it seems natural to me that line 157 should be:

    -np.expand_dims(dx[-1, ], axis=0)),

As if continuing what was taking place in line 156 and then subtracting the final row of the array from zero. **But**, this reasoning does not quite hold, because in this case `dx[-1, ] - dx[-2, ]` is not computed anywhere and it does not seem to make sense to skip that. Based on that, I wonder if line 157 should instead be:

    np.expand_dims(dx[-1, ] - dx[-2, ], axis=0)),

It is quite possible I am just completely mistaken, but if there is something wrong here, the following should be checked as well:
https://github.com/epfl-lts2/pyunlocbox/blob/ee37c50586a445e2a8d851028d5e878a16164e89/pyunlocbox/operators.py#L167-L170
https://github.com/epfl-lts2/pyunlocbox/blob/ee37c50586a445e2a8d851028d5e878a16164e89/pyunlocbox/operators.py#L179-L182
https://github.com/epfl-lts2/pyunlocbox/blob/ee37c50586a445e2a8d851028d5e878a16164e89/pyunlocbox/operators.py#L191-L194

**Comment by nperraud** [comment]
For sure, I understand the confusion... However I believe the code is correct. In this toolbox, divergence is defined as the - grad transposed. I just added this test: https://github.com/epfl-lts2/pyunlocbox/blob/e290b9f4419cff11a024d10239520c81795b2f6a/pyunlocbox/tests/test_operators.py#L404
and it seems to pass...
