### ISSUE TITLE
keep solution only at necessary steps

### ISSUE THREAD

**Issue by matteofrigo** [epfl-lts2/pyunlocbox#18]
If I understand correctly, the solvers keep the solution at every step and return it as a list. This is very useful for debugging and education but can be very memory-heavy in real problems.
For example, I need to solve an optimization problem that has ~2M variables and storing the solution at each step saturates my RAM relatively quickly.

Is there a way to tell the solver to keep only the necessary previous steps?

Thank you for your kind help!

**Comment by rodrigo-pena** [comment]
Hi @matteofrigo, which version of the pyunlocbox are you using? The solvers do not keep track of all the iterates throughout the process, but only the values of the objective function at each iteration. Since the latter are floating-point numbers, this shouldn't be memory-intensive. The only exception is if you set the `xtol` as stopping criteria, but even then only the last and current solutions are kept in memory for comparison.

Could you send a minimum working example showing this behavior you described?

**Comment by matteofrigo** [comment]
Hi @rodrigo-pena , thanks for your answer. I'm using the latest version (at [this](https://github.com/epfl-lts2/pyunlocbox/tree/b22ae58596802f9298abb48e17d41b846f524b43) commit).

I'm having troubles in replicating the bug with a small example, as I'm solving the regularized non-negative least squares with a sparse forward operator whose dimensions are `~1e7` -by- `~1e6` and the regularization term is the group sparsity penalty. I'm using the forward-backward routine with fista+backtracking acceleration. The stopping criterion is set both on `rtol` and `xtol`.

During the optimization I notice a relevant increase of the usage of RAM, which unfortunately I don't notice in small examples. I'll keep trying to create a working example that shows the phenomenon.

The regularization term is implemented as follows.
```
class StructuredSparsity(pyunlocbox.functions.func):
    def __init__(self, regularization_parameter, groups, weights):
                self._regularization_parameter = regularization_parameter
                self._groups = groups
                self._weights = weights


    def _eval(self, x):
        costs = [w * np.sqrt(np.sum(x[g] ** 2))
                 for g, w in zip(self._groups, self._weights)]
        return self._regularization_parameter * np.sum(costs)


    def _prox(self, x, mu):
        v = np.maximum(x, 0.0)
        for g, w in zip(self._groups, self._weights):
            xn = np.sqrt(np.dot(v[g], v[g]))
            r = mu * self.regularization_parameter * w
            if xn > r:
                v[g] -= v[g] * r / xn
            else:
                v[g] = 0.0
        return v
```

**Comment by rodrigo-pena** [comment]
Do you get high RAM usage if you run fista **without** acceleration?

**Comment by mdeff** [comment]
Hi @matteofrigo, could you figure this out?

**Comment by mdeff** [comment]
Please also consider making a PR for your `StructuredSparsity` function. Might be useful to others! :)

**Comment by matteofrigo** [comment]
Hi @mdeff and @rodrigo-pena . Sorry for not getting back. I solved without changing the way I use pyunlockbox. I only re-implemented my forward operator to be more memory efficient and I don't observe the increase in RAM use anymore.

Yes, I should prepare a PR for the StructuredSparsity function. I'll look at the contributing guidelines and do it.

**Comment by matteofrigo** [comment]
I opened #26 that proposes an implementation of the structured sparsity term with tests and documentation.

**Comment by mdeff** [comment]
Good to hear you solved the issue! Thanks for the PR. :+1:
