### ISSUE TITLE
weighted norm minimization

### ISSUE THREAD

**Issue by narges-mhm** [epfl-lts2/pyunlocbox#19]
I have a problem with using weighted-l2. In fact, according to the docs, the dimension of w should be the same as the dimension of y while I get a dimension error. I need to know whether you have tried the weighted ones. The error is exactly in the same part as it is mentioned:
Nati: I've checked this code the use of 'y' seems correct

**Comment by nperraud** [comment]
Yes this has been tested here: https://github.com/epfl-lts2/pyunlocbox/blob/d0bd39b31f412f9c19382089775e0e31b4374c3c/pyunlocbox/tests/test_functions.py#L116

```Nati: I've checked this code the use of 'y' seems correct``` this is actually in the norm_l1

I have added some test in the norm_l1 and did not found any bugs... See this PR: https://github.com/epfl-lts2/pyunlocbox/pull/21

**Comment by narges-mhm** [comment]
Thanks for your response but the error still persists. Suppose A is M*N (where M>N) and consequently x dim would be N*1 and w&y are M*1. In this case:
class norm_l2:
def _prox:
if self.tight:
            sol = x + 2. * gamma * self.At(self.y() * self.w**2)
            sol /= 1. + 2. * gamma * self.nu * self.w**2

from the first line sol is N*1 and in the second line, sol is going to be divide by w which is M*1. And that is why I get dimension error.

**Comment by nperraud** [comment]
Could you simply m

**Comment by narges-mhm** [comment]
https://user-images.githubusercontent.com/61758751/75893435-cbc64100-5e00-11ea-93f4-f3ffdb82c405.JPG

This is an error for norm_l2 and tight=True.

**Comment by nperraud** [comment]
Please copy the code here so I can try it. It is more efficient thant recopying everything for your image.

Le 4 mars 2020 16:17, narges-mhm <notifications@github.com> a écrit :

https://user-images.githubusercontent.com/61758751/75893435-cbc64100-5e00-11ea-93f4-f3ffdb82c405.JPG

This is an error for norm_l2 and tight=True.

**Comment by narges-mhm** [comment]
`w=np.array([1,2,2,1])`
`A=np.random.normal(size=(4,3))`
`x=np.array([1,-1,1])`
`y=A@x`
`f1=functions.norm_l2(A=A,y=y,w=w,tight=True)` 
`f2=functions.dummy()`
`step= 0.5 / np.linalg.norm(A, ord=2)**2` 
`x1=np.array([.2,.2,.2])`
`solver2= solvers.generalized_forward_backward(step=step*0.1)` 
`ret2= solvers.solve([f1,f2], x1, solver2, rtol=1e-6, maxit=1000)` 
`objective2= np.array(ret2['objective'])`

**Comment by nperraud** [comment]
Sorry for my late reply. I was able to reproduce the problem.

One thing that see is that you are using tight=True, which is not correct in your example. Indeed A is not a tight operator. If ignore this, the proximal solution for a tight operator requires a constant weight to be valid. Hence, if tight=True, then w should be a scalar. To solve this problem, you can simply set tight=False in your code.

i will add a check for this in the code such that one cannot define a function with multiple weights and a tight operator.
