### ISSUE TITLE
non-negativity constraint

### ISSUE THREAD

**Issue by narges-mhm** [epfl-lts2/pyunlocbox#20]
I am wondering whether it is possible to implement a non-negativity constraint (x>0) by your toolbox. I was not able to employ it so far.

**Comment by nperraud** [comment]
Hi narges-mhm
That one is easy. There is a PR adding the positivity projection: https://github.com/epfl-lts2/pyunlocbox/pull/10/
Should be merge soon.

**Comment by mdeff** [comment]
I merged #10. Thanks for your patience!
