### ISSUE TITLE
norm l_1 in projection space

### ISSUE THREAD

**Issue by narges-mhm** [epfl-lts2/pyunlocbox#22]
I noticed that if the projection of x be sparse, then we need to minimize this term: \|A(x)\|_1 
while according to provided code in:
class norm_l1:
def _prox:

sol = self.A(x) - self.y()
sol[:] = _soft_threshold(sol, gamma * self.nu * self.w) - sol
sol[:] = x + self.At(sol) / self.nu

if A has a dimension of M*N and x be an N*1 one; then by the first above-mentioned line, sol would have the dimension of M*1 while in the last line the dim of x which is N*1 is not compatible with sol dim.
I would be please if you check it.

**Comment by nperraud** [comment]
Well At is the transpose of A. So `sol[:] = x + self.At(sol) / self.nu`  brings sol back to the right dimension. The code is correct.

**Comment by narges-mhm** [comment]
In the following simple code, my final goal is to minimize f1 which is norm_l1 of projection of sol and I require the 'eval' and 'grad' or 'prox'. While the cap output indicates just "eval" capability so the minimization of l1 failed.
`w=np.array([1,2,2,1])
A=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
x=np.array([1,-1,1])
y=A@x
f1=functions.norm_l1(A=A, y=np.array([0,0,0,0]),tight=False)
f1.cap(x)`

https://user-images.githubusercontent.com/61758751/75898556-3929a000-5e08-11ea-9297-6bfad15bd7ca.JPG

**Comment by nperraud** [comment]
The problem is that a solution for A not tight has not been implemented yet... The thing is that even if we would implement it, it would not be a good solution... It is better to use primal dual aglorithm such as mlfbf. In that case L will be your A.
