### ISSUE TITLE
Is total variation image reconstruction behaving corretly?

### ISSUE THREAD

**Issue by ThomasA** [epfl-lts2/pyunlocbox#3]
I have experimented with total variation image reconstruction based on the example included under `demos`. I have noticed that the reconstructed image exhibits significant artifacts in the horisontal direction but not in the vertical direction.
I had expected that the solver would be using a 2-dimensional gradient under the settings in the demo and that this would cause the algorithm to perform equally well in the vertical as well as the horisontal direction. This does not seem to be the case.
I have run the demo on a checkerboard test image to illustrate the effect more clearly. You can see my modified demo here: https://github.com/ThomasA/pyunlocbox/blob/master/pyunlocbox/demos/demo_douglas_rachford.py
The result is included here:
![checkerboard_test](https://cloud.githubusercontent.com/assets/971307/6068818/794a4c5a-ad7f-11e4-8497-f1efe2b60ee4.png)

**Comment by nperraud** [comment]
Hello

The code is not from me. But I think I can fix this tomorrow. 

I'll also answer your other email before the end of the weekend. 

Cheers 

Nathanael 


Envoyé depuis mon smartphone Samsung Galaxy.


-------- Message d'origine --------
De : Thomas Arildsen <notifications@github.com> 
Date :05/02/2015  21:41  (GMT+01:00) 
À : epfl-lts2/pyunlocbox <pyunlocbox@noreply.github.com> 
Cc :  
Objet : [pyunlocbox] Is total variation image reconstruction behaving
  corretly? (#3) 

I have experimented with total variation image reconstruction based on the example included under demos. I have noticed that the reconstructed image exhibits significant artifacts in the horisontal direction but not in the vertical direction.
I had expected that the solver would be using a 2-dimensional gradient under the settings in the demo and that this would cause the algorithm to perform equally well in the vertical as well as the horisontal direction. This does not seem to be the case.
I have run the demo on a checkerboard test image to illustrate the effect more clearly. You can see my modified demo here: https://github.com/ThomasA/pyunlocbox/blob/master/pyunlocbox/demos/demo_douglas_rachford.py
The result is included here:

**Comment by ThomasA** [comment]
Great, thanks for looking into it.

**Comment by alafaye** [comment]
Fixed
