### ISSUE TITLE
Lena should not be used as test image and should be removed from the package.

### ISSUE THREAD

**Issue by nperraud** [epfl-lts2/pyunlocbox#30]
No comment needed

**Comment by mdeff** [comment]
Agreed. But is `barbara.png` better? Aren't there standard but neutral images? Like a landscape.

**Comment by nperraud** [comment]
Barbara is definitely better. There is no history behind this image. We could use pepper or mandrill. But they are in color...

**Comment by mdeff** [comment]
Ok. Let's go with barbara then.
