### ISSUE TITLE
Problem with the mlfbf solver

### ISSUE THREAD

**Issue by nperraud** [epfl-lts2/pyunlocbox#35]
The solver mlfbf is not giving the right solution, I believe...

```
import numpy as np
from pyunlocbox.functions import norm_l1, norm_l2, dummy
from pyunlocbox.solvers import mlfbf, solve, forward_backward, projection_based, douglas_rachford

n = 1
y = np.ones([n])*2
c = 1


f = norm_l1(lambda_=c/2)
g = norm_l1(lambda_=c/2)
h = norm_l2(lambda_=0.5, y=y)

beta = 1
mu = beta + 1
step = 1 / mu / 2

solver = mlfbf(step=step)
ret = solve([f, g, h], y.copy(), solver, maxit=200, rtol=0)

sol1 = ret["sol"]


f = norm_l1(lambda_=c)
g = dummy()
h = norm_l2(lambda_=0.5, y=y)

beta = 1
mu = beta + 1
step = 1 / mu / 2

solver = mlfbf(step=step)
ret = solve([f, g, h], y.copy(), solver, maxit=200, rtol=0)
sol2 = ret["sol"]

solver = forward_backward()
ret = solve([f, h], y.copy(), solver, maxit=200, rtol=0)
sol3 = ret["sol"]

solver = projection_based()
ret = solve([f, h], y.copy(), solver, maxit=200, rtol=0)
sol4 = ret["sol"]

solver = douglas_rachford()
ret = solve([f, h], y.copy(), solver, maxit=200, rtol=0)
sol5 = ret["sol"]

sol1, sol2, sol3, sol4, sol5
```
produces
```
Solution found after 200 iterations:
    objective function f(sol) = 1.580000e+00
    stopping criterion: MAXIT
Solution found after 200 iterations:
    objective function f(sol) = 1.820000e+00
    stopping criterion: MAXIT
Solution found after 200 iterations:
    objective function f(sol) = 1.500000e+00
    stopping criterion: MAXIT
Solution found after 200 iterations:
    objective function f(sol) = 2.000000e+00
    stopping criterion: MAXIT
Solution found after 200 iterations:
    objective function f(sol) = 1.500000e+00
    stopping criterion: MAXIT
(array([0.6]), array([0.2]), array([1.]), array([0.]), array([1.]))
```

The correct answer is given by forward backward and douglas_rachford. It is 1.

**Comment by nperraud** [comment]
@rodrigo-pena Any idea what is happening?

**Comment by nperraud** [comment]
`projection_based` is also producing weird results...

**Comment by nperraud** [comment]
I found that adding the argument `L=np.eye(n)` to the solver fixes the problem...

**Comment by nperraud** [comment]
@mdeff Any idea why this is happening. And also, is it normal that the input x0 is modified by the algorithm? I believe this can be surprising for the user.

**Comment by nperraud** [comment]
I found the problem. The dual variable and the primal variable becomes the same variable. A small .copy() fix the problem.

**Comment by rodrigo-pena** [comment]
The assignments 
```
        # Update solution (in both primal and dual spaces)
        self.sol[:] = self.sol - y1 + q1
        self.dual_sol[:] = self.dual_sol - y2 + q2
```
in `mlfbf._algo` should already work in not letting the primal and the dual be the same variable, no? Unless I forgot the point of having that `[:]` in the variable assignment.

**Comment by nperraud** [comment]
The problem was in the initialization part of the algorithm. If `L` is `lambda x: x`, the the dual variable and the solution are the same variable.

https://github.com/epfl-lts2/pyunlocbox/blob/f5c1b0159fa617bf029c4fdd50dd3aedd46668e7/pyunlocbox/solvers.py#L783
```
 self.dual_sol = self.L(x_0)
```
My current fix is 
```
self.dual_sol = self.L(np.asarray(x0).copy())
```

**Comment by rodrigo-pena** [comment]
I see. Should we enforce this copy then within the parent class method `primal_dual._pre`?

**Comment by nperraud** [comment]
I think so. I also think that we should not modify x0 in general, which is happening in other (non-primal dual) solver as well. I had the feeling that @mdeff had this design to save memory. So before changing that, we should have his opinion.

**Comment by nperraud** [comment]
Just found another small bug. This does not work because the evaluation function for the solver class does not apply the operator L.
```
import numpy as np
from pyunlocbox import functions, solvers
y = np.array([294, 390, 361])
y_2 = np.zeros([4])
L = np.array([[5, 9, 3], [7, 8, 5], [4, 4, 9], [0, 1, 7]])
x0 = np.zeros(len(y))
f = functions.dummy()
f._prox = lambda x, T: np.maximum(np.zeros(len(x)), x)
g = functions.norm_l2(lambda_=0.5, y=y_2)
h = functions.norm_l2(y=y, lambda_=0.5)
max_step = 1/(1 + np.linalg.norm(L, 2))
solver = solvers.mlfbf(L=L, step=max_step/2.)
ret = solvers.solve([f, g, h], x0, solver, maxit=1000, rtol=0)
```

It is not simple bug to fix because solve is a function and not a class.

**Comment by nperraud** [comment]
@mdeff Would you agree to move the function solve in the class `solver`?

We could still have wrapper function solve to preserve backward compatibility I guess.

**Comment by nperraud** [comment]
I am making a an attempt and will push it in the branch `NMF`. I will let you then complain.

**Comment by mdeff** [comment]
> is it normal that the input x0 is modified by the algorithm? I believe this can be surprising for the user. [...]
> I had the feeling that @mdeff had this design to save memory.

My idea was indeed to change `x0` in-place to save memory. On one hand I agree it might be surprising to mutate data, on the other it saves memory while the content of `x0` is generally of no value. But I don't have strong feelings.
