### ISSUE TITLE
Is the pip version of pyunlocbox up-to-date?

### ISSUE THREAD

**Issue by jacquesdurden** [epfl-lts2/pyunlocbox#37]
It seems that a "pip install" installs pyunlocbox version 0.5.2 but, for instance, functions.py does not include proj_spsd? Do you advise to clone pyunlocbox to get this last version?

**Comment by nperraud** [comment]
I am not sure when we will do a new release. Meanwhile you can use 
```
pip install git+https://github.com/epfl-lts2/pyunlocbox.git
```
