### ISSUE TITLE
Sense of the eval function for projectors?

### ISSUE THREAD

**Issue by jacquesdurden** [epfl-lts2/pyunlocbox#38]
I don't really get the sense of the eval function on "projectors". While the prox of them is clearly the true projector on a set, I would have guessed that their evaluation should be the indicator of the set on which the projection occurs, that is 0 within the set and infinity outside. However, according to the code "eval" always gives 0. What's the reason? Is it necessary to get always 0 for the code to work?

**Comment by nperraud** [comment]
The `eval` function is there for compatibility reasons, i.e. following the structure of all other proximal operators. In theory, it should give either + infinity (outside of the set) or 0 (inside of the set), as projections are the proximal operator of indicator functions. For obvious implementation reason, we keep it to 0.

It does not need to be 0 for the code to work.
