### ISSUE TITLE
How do you define the Lipschitz constant of the gradient (".beta" in the Matlab version)?

### ISSUE THREAD

**Issue by raaupr** [epfl-lts2/pyunlocbox#41]
Hi! Thanks a lot for having a python version of the library!
I'm currently "translating" some Matlab codes that uses your Matlab unlocbox library to python, and I'm not quite sure how to define the Lipschitz constant in the python version? Something that is equal to doing `f2.beta = LIP;` in the Matlab version. I'm sorry if this has been documented somewhere, but I am unable to find this information.
Thank you!

**Comment by nperraud** [comment]
Hi raaupr,

This is a good question. Currently, the pyunlocbox does not support automatic setting of the learning rate. So basically you need to set the step for differentiable terms manually via the argument `step` of the solver. In general you can use step=1/LIP, where LIP is the Lipschitz constant of the differentiable part of your objective function.

Good luck

**Comment by mdeff** [comment]
Hi, thanks for your interest!

As @nperraud said, you should compute the step yourself (with the Lipschitz constant or not) and instantiate the solver with it. You can see how that's done in the following two tutorials:
* [Compressed sensing using forward-backward](https://pyunlocbox.readthedocs.io/en/stable/tutorials/compressed_sensing_forward_backward.html?highlight=Lipschitz)
* [Image reconstruction (Forward-Backward, Total Variation, L2-norm)](https://pyunlocbox.readthedocs.io/en/stable/tutorials/reconstruction.html?highlight=Lipschitz)

Hope that helps!
