### ISSUE TITLE
Are there any plans to port the nuclear norm operator from UNLocBox to PyUNLocBox?

### ISSUE THREAD

**Issue by ThomasA** [epfl-lts2/pyunlocbox#5]

**Comment by nperraud** [comment]
I've just pushed some code on devel. However, it is not fully tested yet.

**Comment by ThomasA** [comment]
Sounds promising. I will check it out. 
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mdeff** [comment]
I've just fixed the unit tests and documentation for the nuclear-norm. Let us know if you encounter any problem ! Meanwhile I'm in the process of preparing a new release, before adding further functionality (I'm also using the toolbox for research).

**Comment by ThomasA** [comment]
Great, I will try it out, probably next week.
